branches:
  only:
    - master
cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules
environment:
  nodejs_version: "12"
init:
  - ps: Install-Product node $env:nodejs_version
  - ps: Write-Host "Installing Yarn!"
  - ps: (New-Object Net.WebClient).DownloadFile("https://yarnpkg.com/latest.msi", "$env:temp\yarn.msi")
  - ps: cmd /c start /wait msiexec.exe /i $env:temp\yarn.msi /quiet /qn /norestart
install:
  - node --version
  - npm --version
  - yarn --version
  - appveyor-retry yarn install --network-concurrency 1
build: off
